// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storedb

import (
	"database/sql"
)

type Channel struct {
	ID               string
	GuildID          string
	ParentID         sql.NullString
	Kind             string
	Name             string
	Topic            sql.NullString
	Position         sql.NullInt64
	IsNsfw           int64
	IsArchived       int64
	IsLocked         int64
	IsPrivateThread  int64
	ThreadParentID   sql.NullString
	ArchiveTimestamp sql.NullString
	RawJson          string
	UpdatedAt        string
}

type EmbeddingJob struct {
	MessageID    string
	State        string
	Attempts     int64
	Provider     string
	Model        string
	InputVersion string
	LastError    string
	LockedAt     sql.NullString
	UpdatedAt    string
}

type FailureLedger struct {
	FailureID    int64
	Operation    string
	Source       string
	GuildID      string
	ChannelID    string
	MessageID    string
	RelatedKind  string
	RelatedID    string
	ErrorClass   string
	ErrorMessage string
	FirstSeenAt  string
	LastSeenAt   string
	RetryCount   int64
	ResolvedAt   sql.NullString
}

type Guild struct {
	ID             string
	Name           string
	Icon           sql.NullString
	RawJson        string
	UpdatedAt      string
	DeletedAt      sql.NullString
	DeletionSource sql.NullString
	DeletionReason sql.NullString
}

type Member struct {
	GuildID        string
	UserID         string
	Username       string
	GlobalName     sql.NullString
	DisplayName    sql.NullString
	Nick           sql.NullString
	Discriminator  sql.NullString
	Avatar         sql.NullString
	Bot            int64
	JoinedAt       sql.NullString
	RoleIdsJson    string
	RawJson        string
	UpdatedAt      string
	DeletedAt      sql.NullString
	DeletionSource sql.NullString
	DeletionReason sql.NullString
}

type MemberFt struct {
	Rowid       int64
	MemberKey   sql.NullString
	GuildID     sql.NullString
	UserID      sql.NullString
	Username    sql.NullString
	DisplayName sql.NullString
	ProfileText sql.NullString
}

type MentionEvent struct {
	EventID    int64
	MessageID  string
	GuildID    string
	ChannelID  string
	AuthorID   sql.NullString
	TargetType string
	TargetID   string
	TargetName string
	EventAt    string
}

type Message struct {
	ID                string
	GuildID           string
	ChannelID         string
	AuthorID          sql.NullString
	MessageType       int64
	CreatedAt         string
	EditedAt          sql.NullString
	DeletedAt         sql.NullString
	Content           string
	NormalizedContent string
	ReplyToMessageID  sql.NullString
	Pinned            int64
	HasAttachments    int64
	RawJson           string
	UpdatedAt         string
}

type MessageAttachment struct {
	AttachmentID  string
	MessageID     string
	GuildID       string
	ChannelID     string
	AuthorID      sql.NullString
	Filename      string
	ContentType   sql.NullString
	Size          int64
	Url           sql.NullString
	ProxyUrl      sql.NullString
	TextContent   string
	MediaPath     sql.NullString
	ContentSha256 sql.NullString
	ContentSize   int64
	FetchedAt     sql.NullString
	FetchStatus   string
	FetchError    string
	UpdatedAt     string
}

type MessageEmbedding struct {
	MessageID     string
	Provider      string
	Model         string
	InputVersion  string
	Dimensions    int64
	EmbeddingBlob []byte
	EmbeddedAt    string
}

type MessageEvent struct {
	EventID     int64
	GuildID     string
	ChannelID   string
	MessageID   string
	EventType   string
	EventAt     string
	PayloadJson string
}

type MessageFt struct {
	Rowid       int64
	MessageID   sql.NullString
	GuildID     sql.NullString
	ChannelID   sql.NullString
	AuthorID    sql.NullString
	AuthorName  sql.NullString
	ChannelName sql.NullString
	Content     sql.NullString
}

type SyncState struct {
	Scope     string
	Cursor    sql.NullString
	UpdatedAt string
}
