// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package storedb

import (
	"context"
	"database/sql"
)

const channelMessageBounds = `-- name: ChannelMessageBounds :one
select cast(coalesce(min(id), '') as text) as oldest_id,
       cast(coalesce(max(id), '') as text) as newest_id
from messages
where channel_id = ?
`

type ChannelMessageBoundsRow struct {
	OldestID string
	NewestID string
}

func (q *Queries) ChannelMessageBounds(ctx context.Context, channelID string) (ChannelMessageBoundsRow, error) {
	row := q.db.QueryRowContext(ctx, channelMessageBounds, channelID)
	var i ChannelMessageBoundsRow
	err := row.Scan(&i.OldestID, &i.NewestID)
	return i, err
}

const countChannels = `-- name: CountChannels :one
select count(*) as count from channels
`

func (q *Queries) CountChannels(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChannels)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countChannelsByGuild = `-- name: CountChannelsByGuild :one
select count(*) as count
from channels
where guild_id = ?
`

func (q *Queries) CountChannelsByGuild(ctx context.Context, guildID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChannelsByGuild, guildID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEmbeddingBacklog = `-- name: CountEmbeddingBacklog :one
select count(*) as count
from embedding_jobs j
join messages m on m.id = j.message_id
where j.state = 'pending'
  and m.deleted_at is null
`

func (q *Queries) CountEmbeddingBacklog(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEmbeddingBacklog)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEmbeddingJobsByMessage = `-- name: CountEmbeddingJobsByMessage :one
select count(*) as count
from embedding_jobs
where message_id = ?
`

func (q *Queries) CountEmbeddingJobsByMessage(ctx context.Context, messageID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEmbeddingJobsByMessage, messageID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGuilds = `-- name: CountGuilds :one
select count(*) as count from guilds
`

func (q *Queries) CountGuilds(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGuilds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMembers = `-- name: CountMembers :one
select count(*) as count from members
`

func (q *Queries) CountMembers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMembers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMembersByGuild = `-- name: CountMembersByGuild :one
select count(*) as count
from members
where guild_id = ?
`

func (q *Queries) CountMembersByGuild(ctx context.Context, guildID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMembersByGuild, guildID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMessages = `-- name: CountMessages :one
select count(*) as count from messages
`

func (q *Queries) CountMessages(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMessages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countThreads = `-- name: CountThreads :one
select count(*) as count
from channels
where kind like 'thread_%'
`

func (q *Queries) CountThreads(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countThreads)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAttachmentsByGuild = `-- name: DeleteAttachmentsByGuild :exec
delete from message_attachments
where guild_id = ?
`

func (q *Queries) DeleteAttachmentsByGuild(ctx context.Context, guildID string) error {
	_, err := q.db.ExecContext(ctx, deleteAttachmentsByGuild, guildID)
	return err
}

const deleteAttachmentsByMessage = `-- name: DeleteAttachmentsByMessage :exec
delete from message_attachments
where message_id = ?
`

func (q *Queries) DeleteAttachmentsByMessage(ctx context.Context, messageID string) error {
	_, err := q.db.ExecContext(ctx, deleteAttachmentsByMessage, messageID)
	return err
}

const deleteChannelsByGuild = `-- name: DeleteChannelsByGuild :exec
delete from channels
where guild_id = ?
`

func (q *Queries) DeleteChannelsByGuild(ctx context.Context, guildID string) error {
	_, err := q.db.ExecContext(ctx, deleteChannelsByGuild, guildID)
	return err
}

const deleteEmbeddingJobsByGuild = `-- name: DeleteEmbeddingJobsByGuild :exec
delete from embedding_jobs
where message_id in (select id from messages where guild_id = ?)
`

func (q *Queries) DeleteEmbeddingJobsByGuild(ctx context.Context, guildID string) error {
	_, err := q.db.ExecContext(ctx, deleteEmbeddingJobsByGuild, guildID)
	return err
}

const deleteGuild = `-- name: DeleteGuild :exec
delete from guilds
where id = ?
`

func (q *Queries) DeleteGuild(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteGuild, id)
	return err
}

const deleteMember = `-- name: DeleteMember :exec
delete from members
where guild_id = ? and user_id = ?
`

type DeleteMemberParams struct {
	GuildID string
	UserID  string
}

func (q *Queries) DeleteMember(ctx context.Context, arg DeleteMemberParams) error {
	_, err := q.db.ExecContext(ctx, deleteMember, arg.GuildID, arg.UserID)
	return err
}

const deleteMembersByGuild = `-- name: DeleteMembersByGuild :exec
delete from members
where guild_id = ?
`

func (q *Queries) DeleteMembersByGuild(ctx context.Context, guildID string) error {
	_, err := q.db.ExecContext(ctx, deleteMembersByGuild, guildID)
	return err
}

const deleteMentionEventsByGuild = `-- name: DeleteMentionEventsByGuild :exec
delete from mention_events
where guild_id = ?
`

func (q *Queries) DeleteMentionEventsByGuild(ctx context.Context, guildID string) error {
	_, err := q.db.ExecContext(ctx, deleteMentionEventsByGuild, guildID)
	return err
}

const deleteMentionEventsByMessage = `-- name: DeleteMentionEventsByMessage :exec
delete from mention_events
where message_id = ?
`

func (q *Queries) DeleteMentionEventsByMessage(ctx context.Context, messageID string) error {
	_, err := q.db.ExecContext(ctx, deleteMentionEventsByMessage, messageID)
	return err
}

const deleteMessageEmbeddingsByGuild = `-- name: DeleteMessageEmbeddingsByGuild :exec
delete from message_embeddings
where message_id in (select id from messages where guild_id = ?)
`

func (q *Queries) DeleteMessageEmbeddingsByGuild(ctx context.Context, guildID string) error {
	_, err := q.db.ExecContext(ctx, deleteMessageEmbeddingsByGuild, guildID)
	return err
}

const deleteMessageEmbeddingsByMessage = `-- name: DeleteMessageEmbeddingsByMessage :exec
delete from message_embeddings
where message_id = ?
`

func (q *Queries) DeleteMessageEmbeddingsByMessage(ctx context.Context, messageID string) error {
	_, err := q.db.ExecContext(ctx, deleteMessageEmbeddingsByMessage, messageID)
	return err
}

const deleteMessageEventsByGuild = `-- name: DeleteMessageEventsByGuild :exec
delete from message_events
where guild_id = ?
`

func (q *Queries) DeleteMessageEventsByGuild(ctx context.Context, guildID string) error {
	_, err := q.db.ExecContext(ctx, deleteMessageEventsByGuild, guildID)
	return err
}

const deleteMessagesByGuild = `-- name: DeleteMessagesByGuild :exec
delete from messages
where guild_id = ?
`

func (q *Queries) DeleteMessagesByGuild(ctx context.Context, guildID string) error {
	_, err := q.db.ExecContext(ctx, deleteMessagesByGuild, guildID)
	return err
}

const deleteOrphanChannels = `-- name: DeleteOrphanChannels :exec
delete from channels
where channels.guild_id = ?
  and not exists (
	select 1
	from messages
	where messages.channel_id = channels.id
  )
`

func (q *Queries) DeleteOrphanChannels(ctx context.Context, guildID string) error {
	_, err := q.db.ExecContext(ctx, deleteOrphanChannels, guildID)
	return err
}

const deleteSyncState = `-- name: DeleteSyncState :exec
delete from sync_state
where scope = ?
`

func (q *Queries) DeleteSyncState(ctx context.Context, scope string) error {
	_, err := q.db.ExecContext(ctx, deleteSyncState, scope)
	return err
}

const getGuildName = `-- name: GetGuildName :one
select name
from guilds
where id = ?
`

func (q *Queries) GetGuildName(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getGuildName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getMessageNormalizedContent = `-- name: GetMessageNormalizedContent :one
select normalized_content
from messages
where id = ?
`

func (q *Queries) GetMessageNormalizedContent(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getMessageNormalizedContent, id)
	var normalized_content string
	err := row.Scan(&normalized_content)
	return normalized_content, err
}

const getSyncState = `-- name: GetSyncState :one
select coalesce(cursor, '') as cursor
from sync_state
where scope = ?
`

func (q *Queries) GetSyncState(ctx context.Context, scope string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSyncState, scope)
	var cursor string
	err := row.Scan(&cursor)
	return cursor, err
}

const getSyncUpdatedAt = `-- name: GetSyncUpdatedAt :one
select coalesce(updated_at, '') as updated_at
from sync_state
where scope = ?
`

func (q *Queries) GetSyncUpdatedAt(ctx context.Context, scope string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSyncUpdatedAt, scope)
	var updated_at string
	err := row.Scan(&updated_at)
	return updated_at, err
}

const hasMessageEmbeddings = `-- name: HasMessageEmbeddings :one
select exists(
	select 1
	from message_embeddings
	where provider = ?
	  and model = ?
	  and input_version = ?
) as present
`

type HasMessageEmbeddingsParams struct {
	Provider     string
	Model        string
	InputVersion string
}

func (q *Queries) HasMessageEmbeddings(ctx context.Context, arg HasMessageEmbeddingsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasMessageEmbeddings, arg.Provider, arg.Model, arg.InputVersion)
	var present bool
	err := row.Scan(&present)
	return present, err
}

const insertMember = `-- name: InsertMember :exec
insert into members(
	guild_id, user_id, username, global_name, display_name, nick, discriminator,
	avatar, bot, joined_at, role_ids_json, raw_json, updated_at
) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertMemberParams struct {
	GuildID       string
	UserID        string
	Username      string
	GlobalName    sql.NullString
	DisplayName   sql.NullString
	Nick          sql.NullString
	Discriminator sql.NullString
	Avatar        sql.NullString
	Bot           int64
	JoinedAt      sql.NullString
	RoleIdsJson   string
	RawJson       string
	UpdatedAt     string
}

func (q *Queries) InsertMember(ctx context.Context, arg InsertMemberParams) error {
	_, err := q.db.ExecContext(ctx, insertMember,
		arg.GuildID,
		arg.UserID,
		arg.Username,
		arg.GlobalName,
		arg.DisplayName,
		arg.Nick,
		arg.Discriminator,
		arg.Avatar,
		arg.Bot,
		arg.JoinedAt,
		arg.RoleIdsJson,
		arg.RawJson,
		arg.UpdatedAt,
	)
	return err
}

const insertMentionEvent = `-- name: InsertMentionEvent :exec
insert into mention_events(
	message_id, guild_id, channel_id, author_id, target_type, target_id, target_name, event_at
) values(?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertMentionEventParams struct {
	MessageID  string
	GuildID    string
	ChannelID  string
	AuthorID   sql.NullString
	TargetType string
	TargetID   string
	TargetName string
	EventAt    string
}

func (q *Queries) InsertMentionEvent(ctx context.Context, arg InsertMentionEventParams) error {
	_, err := q.db.ExecContext(ctx, insertMentionEvent,
		arg.MessageID,
		arg.GuildID,
		arg.ChannelID,
		arg.AuthorID,
		arg.TargetType,
		arg.TargetID,
		arg.TargetName,
		arg.EventAt,
	)
	return err
}

const insertMessageAttachment = `-- name: InsertMessageAttachment :exec
insert into message_attachments(
	attachment_id, message_id, guild_id, channel_id, author_id, filename,
	content_type, size, url, proxy_url, text_content, media_path, content_sha256,
	content_size, fetched_at, fetch_status, fetch_error, updated_at
) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
on conflict(attachment_id) do update set
	message_id = excluded.message_id,
	guild_id = excluded.guild_id,
	channel_id = excluded.channel_id,
	author_id = excluded.author_id,
	filename = excluded.filename,
	content_type = excluded.content_type,
	size = excluded.size,
	url = excluded.url,
	proxy_url = excluded.proxy_url,
	text_content = excluded.text_content,
	media_path = coalesce(excluded.media_path, message_attachments.media_path),
	content_sha256 = coalesce(excluded.content_sha256, message_attachments.content_sha256),
	content_size = case
		when excluded.content_size > 0 then excluded.content_size
		else message_attachments.content_size
	end,
	fetched_at = coalesce(excluded.fetched_at, message_attachments.fetched_at),
	fetch_status = case
		when excluded.fetch_status <> '' then excluded.fetch_status
		else message_attachments.fetch_status
	end,
	fetch_error = case
		when excluded.fetch_status <> '' or excluded.fetch_error <> '' then excluded.fetch_error
		else message_attachments.fetch_error
	end,
	updated_at = excluded.updated_at
`

type InsertMessageAttachmentParams struct {
	AttachmentID  string
	MessageID     string
	GuildID       string
	ChannelID     string
	AuthorID      sql.NullString
	Filename      string
	ContentType   sql.NullString
	Size          int64
	Url           sql.NullString
	ProxyUrl      sql.NullString
	TextContent   string
	MediaPath     sql.NullString
	ContentSha256 sql.NullString
	ContentSize   int64
	FetchedAt     sql.NullString
	FetchStatus   string
	FetchError    string
	UpdatedAt     string
}

func (q *Queries) InsertMessageAttachment(ctx context.Context, arg InsertMessageAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, insertMessageAttachment,
		arg.AttachmentID,
		arg.MessageID,
		arg.GuildID,
		arg.ChannelID,
		arg.AuthorID,
		arg.Filename,
		arg.ContentType,
		arg.Size,
		arg.Url,
		arg.ProxyUrl,
		arg.TextContent,
		arg.MediaPath,
		arg.ContentSha256,
		arg.ContentSize,
		arg.FetchedAt,
		arg.FetchStatus,
		arg.FetchError,
		arg.UpdatedAt,
	)
	return err
}

const insertMessageEvent = `-- name: InsertMessageEvent :exec
insert into message_events(guild_id, channel_id, message_id, event_type, event_at, payload_json)
values(?, ?, ?, ?, ?, ?)
`

type InsertMessageEventParams struct {
	GuildID     string
	ChannelID   string
	MessageID   string
	EventType   string
	EventAt     string
	PayloadJson string
}

func (q *Queries) InsertMessageEvent(ctx context.Context, arg InsertMessageEventParams) error {
	_, err := q.db.ExecContext(ctx, insertMessageEvent,
		arg.GuildID,
		arg.ChannelID,
		arg.MessageID,
		arg.EventType,
		arg.EventAt,
		arg.PayloadJson,
	)
	return err
}

const insertMissingEmbeddingJobs = `-- name: InsertMissingEmbeddingJobs :exec
insert or ignore into embedding_jobs(
	message_id, state, attempts, provider, model, input_version, last_error, locked_at, updated_at
)
select id, 'pending', 0, ?, ?, ?, '', null, ?
from messages
where deleted_at is null
`

type InsertMissingEmbeddingJobsParams struct {
	Provider     string
	Model        string
	InputVersion string
	UpdatedAt    string
}

func (q *Queries) InsertMissingEmbeddingJobs(ctx context.Context, arg InsertMissingEmbeddingJobsParams) error {
	_, err := q.db.ExecContext(ctx, insertMissingEmbeddingJobs,
		arg.Provider,
		arg.Model,
		arg.InputVersion,
		arg.UpdatedAt,
	)
	return err
}

const listChannels = `-- name: ListChannels :many
select id, guild_id, coalesce(parent_id, '') as parent_id, kind, name,
       coalesce(topic, '') as topic, position, is_nsfw, is_archived,
       is_locked, is_private_thread, coalesce(thread_parent_id, '') as thread_parent_id,
       coalesce(archive_timestamp, '') as archive_timestamp
from channels
order by guild_id, position, name
`

type ListChannelsRow struct {
	ID               string
	GuildID          string
	ParentID         string
	Kind             string
	Name             string
	Topic            string
	Position         sql.NullInt64
	IsNsfw           int64
	IsArchived       int64
	IsLocked         int64
	IsPrivateThread  int64
	ThreadParentID   string
	ArchiveTimestamp string
}

func (q *Queries) ListChannels(ctx context.Context) ([]ListChannelsRow, error) {
	rows, err := q.db.QueryContext(ctx, listChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelsRow
	for rows.Next() {
		var i ListChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.ParentID,
			&i.Kind,
			&i.Name,
			&i.Topic,
			&i.Position,
			&i.IsNsfw,
			&i.IsArchived,
			&i.IsLocked,
			&i.IsPrivateThread,
			&i.ThreadParentID,
			&i.ArchiveTimestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelsByGuild = `-- name: ListChannelsByGuild :many
select id, guild_id, coalesce(parent_id, '') as parent_id, kind, name,
       coalesce(topic, '') as topic, position, is_nsfw, is_archived,
       is_locked, is_private_thread, coalesce(thread_parent_id, '') as thread_parent_id,
       coalesce(archive_timestamp, '') as archive_timestamp
from channels
where guild_id = ?
order by guild_id, position, name
`

type ListChannelsByGuildRow struct {
	ID               string
	GuildID          string
	ParentID         string
	Kind             string
	Name             string
	Topic            string
	Position         sql.NullInt64
	IsNsfw           int64
	IsArchived       int64
	IsLocked         int64
	IsPrivateThread  int64
	ThreadParentID   string
	ArchiveTimestamp string
}

func (q *Queries) ListChannelsByGuild(ctx context.Context, guildID string) ([]ListChannelsByGuildRow, error) {
	rows, err := q.db.QueryContext(ctx, listChannelsByGuild, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelsByGuildRow
	for rows.Next() {
		var i ListChannelsByGuildRow
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.ParentID,
			&i.Kind,
			&i.Name,
			&i.Topic,
			&i.Position,
			&i.IsNsfw,
			&i.IsArchived,
			&i.IsLocked,
			&i.IsPrivateThread,
			&i.ThreadParentID,
			&i.ArchiveTimestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExistingAttachmentMedia = `-- name: ListExistingAttachmentMedia :many
select attachment_id, coalesce(media_path, '') as media_path,
       coalesce(content_sha256, '') as content_sha256, content_size,
       coalesce(fetched_at, '') as fetched_at, coalesce(fetch_status, '') as fetch_status,
       coalesce(fetch_error, '') as fetch_error
from message_attachments
where message_id = ?
`

type ListExistingAttachmentMediaRow struct {
	AttachmentID  string
	MediaPath     string
	ContentSha256 string
	ContentSize   int64
	FetchedAt     string
	FetchStatus   string
	FetchError    string
}

func (q *Queries) ListExistingAttachmentMedia(ctx context.Context, messageID string) ([]ListExistingAttachmentMediaRow, error) {
	rows, err := q.db.QueryContext(ctx, listExistingAttachmentMedia, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExistingAttachmentMediaRow
	for rows.Next() {
		var i ListExistingAttachmentMediaRow
		if err := rows.Scan(
			&i.AttachmentID,
			&i.MediaPath,
			&i.ContentSha256,
			&i.ContentSize,
			&i.FetchedAt,
			&i.FetchStatus,
			&i.FetchError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuildIDs = `-- name: ListGuildIDs :many
select id
from guilds
order by id
`

func (q *Queries) ListGuildIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listGuildIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncompleteMessageChannelIDs = `-- name: ListIncompleteMessageChannelIDs :many
select c.id
from channels c
where c.kind in ('text', 'news', 'announcement', 'thread_public', 'thread_private', 'thread_news', 'thread_announcement')
  and not exists (
	select 1
	from sync_state s
	where s.scope = 'channel:' || c.id || ':history_complete'
  )
  and not exists (
	select 1
	from sync_state s
	where s.scope = 'channel:' || c.id || ':unavailable'
  )
order by c.id
`

func (q *Queries) ListIncompleteMessageChannelIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listIncompleteMessageChannelIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncompleteMessageChannelIDsByGuild = `-- name: ListIncompleteMessageChannelIDsByGuild :many
select c.id
from channels c
where c.kind in ('text', 'news', 'announcement', 'thread_public', 'thread_private', 'thread_news', 'thread_announcement')
  and c.guild_id = ?
  and not exists (
	select 1
	from sync_state s
	where s.scope = 'channel:' || c.id || ':history_complete'
  )
  and not exists (
	select 1
	from sync_state s
	where s.scope = 'channel:' || c.id || ':unavailable'
  )
order by c.id
`

func (q *Queries) ListIncompleteMessageChannelIDsByGuild(ctx context.Context, guildID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listIncompleteMessageChannelIDsByGuild, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
select guild_id, user_id, username, coalesce(global_name, '') as global_name,
       coalesce(display_name, '') as display_name, coalesce(nick, '') as nick,
       coalesce(discriminator, '') as discriminator, coalesce(avatar, '') as avatar,
       role_ids_json, bot, coalesce(joined_at, '') as joined_at, raw_json
from members
order by coalesce(nullif(display_name, ''), nullif(nick, ''), nullif(global_name, ''), username), username
limit ?
`

type ListMembersRow struct {
	GuildID       string
	UserID        string
	Username      string
	GlobalName    string
	DisplayName   string
	Nick          string
	Discriminator string
	Avatar        string
	RoleIdsJson   string
	Bot           int64
	JoinedAt      string
	RawJson       string
}

func (q *Queries) ListMembers(ctx context.Context, limit int64) ([]ListMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listMembers, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersRow
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.GuildID,
			&i.UserID,
			&i.Username,
			&i.GlobalName,
			&i.DisplayName,
			&i.Nick,
			&i.Discriminator,
			&i.Avatar,
			&i.RoleIdsJson,
			&i.Bot,
			&i.JoinedAt,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembersByGuild = `-- name: ListMembersByGuild :many
select guild_id, user_id, username, coalesce(global_name, '') as global_name,
       coalesce(display_name, '') as display_name, coalesce(nick, '') as nick,
       coalesce(discriminator, '') as discriminator, coalesce(avatar, '') as avatar,
       role_ids_json, bot, coalesce(joined_at, '') as joined_at, raw_json
from members
where guild_id = ?
order by coalesce(nullif(display_name, ''), nullif(nick, ''), nullif(global_name, ''), username), username
limit ?
`

type ListMembersByGuildParams struct {
	GuildID string
	Limit   int64
}

type ListMembersByGuildRow struct {
	GuildID       string
	UserID        string
	Username      string
	GlobalName    string
	DisplayName   string
	Nick          string
	Discriminator string
	Avatar        string
	RoleIdsJson   string
	Bot           int64
	JoinedAt      string
	RawJson       string
}

func (q *Queries) ListMembersByGuild(ctx context.Context, arg ListMembersByGuildParams) ([]ListMembersByGuildRow, error) {
	rows, err := q.db.QueryContext(ctx, listMembersByGuild, arg.GuildID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersByGuildRow
	for rows.Next() {
		var i ListMembersByGuildRow
		if err := rows.Scan(
			&i.GuildID,
			&i.UserID,
			&i.Username,
			&i.GlobalName,
			&i.DisplayName,
			&i.Nick,
			&i.Discriminator,
			&i.Avatar,
			&i.RoleIdsJson,
			&i.Bot,
			&i.JoinedAt,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembersByUserID = `-- name: ListMembersByUserID :many
select guild_id, user_id, username, coalesce(global_name, '') as global_name,
       coalesce(display_name, '') as display_name, coalesce(nick, '') as nick,
       coalesce(discriminator, '') as discriminator, coalesce(avatar, '') as avatar,
       role_ids_json, bot, coalesce(joined_at, '') as joined_at, raw_json
from members
where user_id = ?
order by guild_id, username
`

type ListMembersByUserIDRow struct {
	GuildID       string
	UserID        string
	Username      string
	GlobalName    string
	DisplayName   string
	Nick          string
	Discriminator string
	Avatar        string
	RoleIdsJson   string
	Bot           int64
	JoinedAt      string
	RawJson       string
}

func (q *Queries) ListMembersByUserID(ctx context.Context, userID string) ([]ListMembersByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listMembersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersByUserIDRow
	for rows.Next() {
		var i ListMembersByUserIDRow
		if err := rows.Scan(
			&i.GuildID,
			&i.UserID,
			&i.Username,
			&i.GlobalName,
			&i.DisplayName,
			&i.Nick,
			&i.Discriminator,
			&i.Avatar,
			&i.RoleIdsJson,
			&i.Bot,
			&i.JoinedAt,
			&i.RawJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingEmbeddingJobs = `-- name: ListPendingEmbeddingJobs :many
select
	j.message_id,
	m.normalized_content,
	j.attempts,
	j.provider,
	j.model,
	j.input_version
from embedding_jobs j
join messages m on m.id = j.message_id
where j.state = 'pending'
  and m.deleted_at is null
  and (j.locked_at is null or j.locked_at = '' or j.locked_at < ?)
order by j.updated_at, j.message_id
limit ?
`

type ListPendingEmbeddingJobsParams struct {
	LockedAt sql.NullString
	Limit    int64
}

type ListPendingEmbeddingJobsRow struct {
	MessageID         string
	NormalizedContent string
	Attempts          int64
	Provider          string
	Model             string
	InputVersion      string
}

func (q *Queries) ListPendingEmbeddingJobs(ctx context.Context, arg ListPendingEmbeddingJobsParams) ([]ListPendingEmbeddingJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingEmbeddingJobs, arg.LockedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingEmbeddingJobsRow
	for rows.Next() {
		var i ListPendingEmbeddingJobsRow
		if err := rows.Scan(
			&i.MessageID,
			&i.NormalizedContent,
			&i.Attempts,
			&i.Provider,
			&i.Model,
			&i.InputVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentMemberMessages = `-- name: ListRecentMemberMessages :many
select
	m.id as message_id,
	m.guild_id,
	m.channel_id,
	coalesce(c.name, '') as channel_name,
	coalesce(m.author_id, '') as author_id,
	cast(coalesce(
		nullif(mem.display_name, ''),
		nullif(mem.nick, ''),
		nullif(mem.global_name, ''),
		nullif(mem.username, ''),
		nullif(json_extract(m.raw_json, '$.author.global_name'), ''),
		nullif(json_extract(m.raw_json, '$.author.username'), ''),
		''
	) as text) as author_name,
	cast(case
		when trim(coalesce(m.content, '')) <> '' then m.content
		else m.normalized_content
	end as text) as content,
	m.created_at,
	coalesce(m.reply_to_message_id, '') as reply_to_message,
	m.has_attachments,
	m.pinned
from messages m
left join channels c on c.id = m.channel_id
left join members mem on mem.guild_id = m.guild_id and mem.user_id = m.author_id
where m.guild_id = ? and m.author_id = ?
order by m.created_at desc, m.id desc
limit ?
`

type ListRecentMemberMessagesParams struct {
	GuildID  string
	AuthorID sql.NullString
	Limit    int64
}

type ListRecentMemberMessagesRow struct {
	MessageID      string
	GuildID        string
	ChannelID      string
	ChannelName    string
	AuthorID       string
	AuthorName     string
	Content        string
	CreatedAt      string
	ReplyToMessage string
	HasAttachments int64
	Pinned         int64
}

func (q *Queries) ListRecentMemberMessages(ctx context.Context, arg ListRecentMemberMessagesParams) ([]ListRecentMemberMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentMemberMessages, arg.GuildID, arg.AuthorID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentMemberMessagesRow
	for rows.Next() {
		var i ListRecentMemberMessagesRow
		if err := rows.Scan(
			&i.MessageID,
			&i.GuildID,
			&i.ChannelID,
			&i.ChannelName,
			&i.AuthorID,
			&i.AuthorName,
			&i.Content,
			&i.CreatedAt,
			&i.ReplyToMessage,
			&i.HasAttachments,
			&i.Pinned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEmbeddingJob = `-- name: LockEmbeddingJob :execrows
update embedding_jobs
set locked_at = ?1, updated_at = ?2
where message_id = ?3
  and state = 'pending'
  and (locked_at is null or locked_at = '' or locked_at < ?4)
`

type LockEmbeddingJobParams struct {
	LockedAt    sql.NullString
	UpdatedAt   string
	MessageID   string
	StaleBefore sql.NullString
}

func (q *Queries) LockEmbeddingJob(ctx context.Context, arg LockEmbeddingJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, lockEmbeddingJob,
		arg.LockedAt,
		arg.UpdatedAt,
		arg.MessageID,
		arg.StaleBefore,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markEmbeddingJobDone = `-- name: MarkEmbeddingJobDone :exec
update embedding_jobs
set state = 'done',
	attempts = 0,
	provider = ?,
	model = ?,
	input_version = ?,
	last_error = '',
	locked_at = null,
	updated_at = ?
where message_id = ?
`

type MarkEmbeddingJobDoneParams struct {
	Provider     string
	Model        string
	InputVersion string
	UpdatedAt    string
	MessageID    string
}

func (q *Queries) MarkEmbeddingJobDone(ctx context.Context, arg MarkEmbeddingJobDoneParams) error {
	_, err := q.db.ExecContext(ctx, markEmbeddingJobDone,
		arg.Provider,
		arg.Model,
		arg.InputVersion,
		arg.UpdatedAt,
		arg.MessageID,
	)
	return err
}

const markEmbeddingJobFailed = `-- name: MarkEmbeddingJobFailed :exec
update embedding_jobs
set state = ?,
	attempts = ?,
	provider = ?,
	model = ?,
	input_version = ?,
	last_error = ?,
	locked_at = null,
	updated_at = ?
where message_id = ?
`

type MarkEmbeddingJobFailedParams struct {
	State        string
	Attempts     int64
	Provider     string
	Model        string
	InputVersion string
	LastError    string
	UpdatedAt    string
	MessageID    string
}

func (q *Queries) MarkEmbeddingJobFailed(ctx context.Context, arg MarkEmbeddingJobFailedParams) error {
	_, err := q.db.ExecContext(ctx, markEmbeddingJobFailed,
		arg.State,
		arg.Attempts,
		arg.Provider,
		arg.Model,
		arg.InputVersion,
		arg.LastError,
		arg.UpdatedAt,
		arg.MessageID,
	)
	return err
}

const markEmbeddingJobRateLimited = `-- name: MarkEmbeddingJobRateLimited :exec
update embedding_jobs
set state = 'pending',
	provider = ?,
	model = ?,
	input_version = ?,
	last_error = ?,
	locked_at = null,
	updated_at = ?
where message_id = ?
`

type MarkEmbeddingJobRateLimitedParams struct {
	Provider     string
	Model        string
	InputVersion string
	LastError    string
	UpdatedAt    string
	MessageID    string
}

func (q *Queries) MarkEmbeddingJobRateLimited(ctx context.Context, arg MarkEmbeddingJobRateLimitedParams) error {
	_, err := q.db.ExecContext(ctx, markEmbeddingJobRateLimited,
		arg.Provider,
		arg.Model,
		arg.InputVersion,
		arg.LastError,
		arg.UpdatedAt,
		arg.MessageID,
	)
	return err
}

const markEmptyEmbeddingJobDone = `-- name: MarkEmptyEmbeddingJobDone :exec
update embedding_jobs
set state = 'done',
	provider = ?,
	model = ?,
	input_version = ?,
	last_error = '',
	locked_at = null,
	updated_at = ?
where message_id = ?
`

type MarkEmptyEmbeddingJobDoneParams struct {
	Provider     string
	Model        string
	InputVersion string
	UpdatedAt    string
	MessageID    string
}

func (q *Queries) MarkEmptyEmbeddingJobDone(ctx context.Context, arg MarkEmptyEmbeddingJobDoneParams) error {
	_, err := q.db.ExecContext(ctx, markEmptyEmbeddingJobDone,
		arg.Provider,
		arg.Model,
		arg.InputVersion,
		arg.UpdatedAt,
		arg.MessageID,
	)
	return err
}

const markMessageDeleted = `-- name: MarkMessageDeleted :exec
update messages
set deleted_at = ?, updated_at = ?
where id = ?
`

type MarkMessageDeletedParams struct {
	DeletedAt sql.NullString
	UpdatedAt string
	ID        string
}

func (q *Queries) MarkMessageDeleted(ctx context.Context, arg MarkMessageDeletedParams) error {
	_, err := q.db.ExecContext(ctx, markMessageDeleted, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	return err
}

const memberMessageStats = `-- name: MemberMessageStats :one
select count(*) as message_count,
       cast(coalesce(min(created_at), '') as text) as first_message_at,
       cast(coalesce(max(created_at), '') as text) as last_message_at
from messages
where guild_id = ? and author_id = ?
`

type MemberMessageStatsParams struct {
	GuildID  string
	AuthorID sql.NullString
}

type MemberMessageStatsRow struct {
	MessageCount   int64
	FirstMessageAt string
	LastMessageAt  string
}

func (q *Queries) MemberMessageStats(ctx context.Context, arg MemberMessageStatsParams) (MemberMessageStatsRow, error) {
	row := q.db.QueryRowContext(ctx, memberMessageStats, arg.GuildID, arg.AuthorID)
	var i MemberMessageStatsRow
	err := row.Scan(&i.MessageCount, &i.FirstMessageAt, &i.LastMessageAt)
	return i, err
}

const requeueAllEmbeddingJobs = `-- name: RequeueAllEmbeddingJobs :execrows
update embedding_jobs
set state = 'pending',
	attempts = 0,
	provider = ?,
	model = ?,
	input_version = ?,
	last_error = '',
	locked_at = null,
	updated_at = ?
where message_id in (select id from messages where deleted_at is null)
`

type RequeueAllEmbeddingJobsParams struct {
	Provider     string
	Model        string
	InputVersion string
	UpdatedAt    string
}

func (q *Queries) RequeueAllEmbeddingJobs(ctx context.Context, arg RequeueAllEmbeddingJobsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, requeueAllEmbeddingJobs,
		arg.Provider,
		arg.Model,
		arg.InputVersion,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const resetEmbeddingJobIdentity = `-- name: ResetEmbeddingJobIdentity :exec
update embedding_jobs
set provider = ?,
	model = ?,
	input_version = ?,
	last_error = '',
	locked_at = null,
	updated_at = ?
where message_id = ?
`

type ResetEmbeddingJobIdentityParams struct {
	Provider     string
	Model        string
	InputVersion string
	UpdatedAt    string
	MessageID    string
}

func (q *Queries) ResetEmbeddingJobIdentity(ctx context.Context, arg ResetEmbeddingJobIdentityParams) error {
	_, err := q.db.ExecContext(ctx, resetEmbeddingJobIdentity,
		arg.Provider,
		arg.Model,
		arg.InputVersion,
		arg.UpdatedAt,
		arg.MessageID,
	)
	return err
}

const resetEmbeddingJobIdentityAndAttempts = `-- name: ResetEmbeddingJobIdentityAndAttempts :exec
update embedding_jobs
set provider = ?,
	model = ?,
	input_version = ?,
	attempts = 0,
	last_error = '',
	locked_at = null,
	updated_at = ?
where message_id = ?
`

type ResetEmbeddingJobIdentityAndAttemptsParams struct {
	Provider     string
	Model        string
	InputVersion string
	UpdatedAt    string
	MessageID    string
}

func (q *Queries) ResetEmbeddingJobIdentityAndAttempts(ctx context.Context, arg ResetEmbeddingJobIdentityAndAttemptsParams) error {
	_, err := q.db.ExecContext(ctx, resetEmbeddingJobIdentityAndAttempts,
		arg.Provider,
		arg.Model,
		arg.InputVersion,
		arg.UpdatedAt,
		arg.MessageID,
	)
	return err
}

const setSyncState = `-- name: SetSyncState :exec
insert into sync_state(scope, cursor, updated_at)
values(?, ?, ?)
on conflict(scope) do update set
	cursor = excluded.cursor,
	updated_at = excluded.updated_at
`

type SetSyncStateParams struct {
	Scope     string
	Cursor    sql.NullString
	UpdatedAt string
}

func (q *Queries) SetSyncState(ctx context.Context, arg SetSyncStateParams) error {
	_, err := q.db.ExecContext(ctx, setSyncState, arg.Scope, arg.Cursor, arg.UpdatedAt)
	return err
}

const updateAttachmentFetchStatus = `-- name: UpdateAttachmentFetchStatus :exec
update message_attachments
set fetched_at = ?,
    fetch_status = ?,
    fetch_error = ?,
    updated_at = ?
where attachment_id = ?
`

type UpdateAttachmentFetchStatusParams struct {
	FetchedAt    sql.NullString
	FetchStatus  string
	FetchError   string
	UpdatedAt    string
	AttachmentID string
}

func (q *Queries) UpdateAttachmentFetchStatus(ctx context.Context, arg UpdateAttachmentFetchStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateAttachmentFetchStatus,
		arg.FetchedAt,
		arg.FetchStatus,
		arg.FetchError,
		arg.UpdatedAt,
		arg.AttachmentID,
	)
	return err
}

const updateAttachmentMedia = `-- name: UpdateAttachmentMedia :exec
update message_attachments
set media_path = ?,
    content_sha256 = ?,
    content_size = ?,
    fetched_at = ?,
    fetch_status = ?,
    fetch_error = ?,
    updated_at = ?
where attachment_id = ?
`

type UpdateAttachmentMediaParams struct {
	MediaPath     sql.NullString
	ContentSha256 sql.NullString
	ContentSize   int64
	FetchedAt     sql.NullString
	FetchStatus   string
	FetchError    string
	UpdatedAt     string
	AttachmentID  string
}

func (q *Queries) UpdateAttachmentMedia(ctx context.Context, arg UpdateAttachmentMediaParams) error {
	_, err := q.db.ExecContext(ctx, updateAttachmentMedia,
		arg.MediaPath,
		arg.ContentSha256,
		arg.ContentSize,
		arg.FetchedAt,
		arg.FetchStatus,
		arg.FetchError,
		arg.UpdatedAt,
		arg.AttachmentID,
	)
	return err
}

const upsertChannel = `-- name: UpsertChannel :exec
insert into channels(
	id, guild_id, parent_id, kind, name, topic, position, is_nsfw,
	is_archived, is_locked, is_private_thread, thread_parent_id,
	archive_timestamp, raw_json, updated_at
) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
on conflict(id) do update set
	guild_id = excluded.guild_id,
	parent_id = excluded.parent_id,
	kind = excluded.kind,
	name = excluded.name,
	topic = excluded.topic,
	position = excluded.position,
	is_nsfw = excluded.is_nsfw,
	is_archived = excluded.is_archived,
	is_locked = excluded.is_locked,
	is_private_thread = excluded.is_private_thread,
	thread_parent_id = excluded.thread_parent_id,
	archive_timestamp = excluded.archive_timestamp,
	raw_json = excluded.raw_json,
	updated_at = excluded.updated_at
`

type UpsertChannelParams struct {
	ID               string
	GuildID          string
	ParentID         sql.NullString
	Kind             string
	Name             string
	Topic            sql.NullString
	Position         sql.NullInt64
	IsNsfw           int64
	IsArchived       int64
	IsLocked         int64
	IsPrivateThread  int64
	ThreadParentID   sql.NullString
	ArchiveTimestamp sql.NullString
	RawJson          string
	UpdatedAt        string
}

func (q *Queries) UpsertChannel(ctx context.Context, arg UpsertChannelParams) error {
	_, err := q.db.ExecContext(ctx, upsertChannel,
		arg.ID,
		arg.GuildID,
		arg.ParentID,
		arg.Kind,
		arg.Name,
		arg.Topic,
		arg.Position,
		arg.IsNsfw,
		arg.IsArchived,
		arg.IsLocked,
		arg.IsPrivateThread,
		arg.ThreadParentID,
		arg.ArchiveTimestamp,
		arg.RawJson,
		arg.UpdatedAt,
	)
	return err
}

const upsertEmbeddingJobPending = `-- name: UpsertEmbeddingJobPending :exec
insert into embedding_jobs(message_id, state, attempts, updated_at)
values(?, 'pending', 0, ?)
on conflict(message_id) do update set
	state = 'pending',
	attempts = 0,
	last_error = '',
	locked_at = null,
	updated_at = excluded.updated_at
`

type UpsertEmbeddingJobPendingParams struct {
	MessageID string
	UpdatedAt string
}

func (q *Queries) UpsertEmbeddingJobPending(ctx context.Context, arg UpsertEmbeddingJobPendingParams) error {
	_, err := q.db.ExecContext(ctx, upsertEmbeddingJobPending, arg.MessageID, arg.UpdatedAt)
	return err
}

const upsertGuild = `-- name: UpsertGuild :exec
insert into guilds(id, name, icon, raw_json, updated_at)
values(?, ?, ?, ?, ?)
on conflict(id) do update set
	name = excluded.name,
	icon = excluded.icon,
	raw_json = excluded.raw_json,
	updated_at = excluded.updated_at
`

type UpsertGuildParams struct {
	ID        string
	Name      string
	Icon      sql.NullString
	RawJson   string
	UpdatedAt string
}

func (q *Queries) UpsertGuild(ctx context.Context, arg UpsertGuildParams) error {
	_, err := q.db.ExecContext(ctx, upsertGuild,
		arg.ID,
		arg.Name,
		arg.Icon,
		arg.RawJson,
		arg.UpdatedAt,
	)
	return err
}

const upsertMember = `-- name: UpsertMember :exec
insert into members(
	guild_id, user_id, username, global_name, display_name, nick, discriminator,
	avatar, bot, joined_at, role_ids_json, raw_json, updated_at
) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
on conflict(guild_id, user_id) do update set
	username = excluded.username,
	global_name = excluded.global_name,
	display_name = excluded.display_name,
	nick = excluded.nick,
	discriminator = excluded.discriminator,
	avatar = excluded.avatar,
	bot = excluded.bot,
	joined_at = excluded.joined_at,
	role_ids_json = excluded.role_ids_json,
	raw_json = excluded.raw_json,
	updated_at = excluded.updated_at
`

type UpsertMemberParams struct {
	GuildID       string
	UserID        string
	Username      string
	GlobalName    sql.NullString
	DisplayName   sql.NullString
	Nick          sql.NullString
	Discriminator sql.NullString
	Avatar        sql.NullString
	Bot           int64
	JoinedAt      sql.NullString
	RoleIdsJson   string
	RawJson       string
	UpdatedAt     string
}

func (q *Queries) UpsertMember(ctx context.Context, arg UpsertMemberParams) error {
	_, err := q.db.ExecContext(ctx, upsertMember,
		arg.GuildID,
		arg.UserID,
		arg.Username,
		arg.GlobalName,
		arg.DisplayName,
		arg.Nick,
		arg.Discriminator,
		arg.Avatar,
		arg.Bot,
		arg.JoinedAt,
		arg.RoleIdsJson,
		arg.RawJson,
		arg.UpdatedAt,
	)
	return err
}

const upsertMessage = `-- name: UpsertMessage :exec
insert into messages(
	id, guild_id, channel_id, author_id, message_type, created_at, edited_at, deleted_at,
	content, normalized_content, reply_to_message_id, pinned, has_attachments, raw_json, updated_at
) values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
on conflict(id) do update set
	guild_id = excluded.guild_id,
	channel_id = excluded.channel_id,
	author_id = excluded.author_id,
	message_type = excluded.message_type,
	created_at = excluded.created_at,
	edited_at = excluded.edited_at,
	deleted_at = coalesce(excluded.deleted_at, messages.deleted_at),
	content = excluded.content,
	normalized_content = excluded.normalized_content,
	reply_to_message_id = excluded.reply_to_message_id,
	pinned = excluded.pinned,
	has_attachments = excluded.has_attachments,
	raw_json = excluded.raw_json,
	updated_at = excluded.updated_at
`

type UpsertMessageParams struct {
	ID                string
	GuildID           string
	ChannelID         string
	AuthorID          sql.NullString
	MessageType       int64
	CreatedAt         string
	EditedAt          sql.NullString
	DeletedAt         sql.NullString
	Content           string
	NormalizedContent string
	ReplyToMessageID  sql.NullString
	Pinned            int64
	HasAttachments    int64
	RawJson           string
	UpdatedAt         string
}

func (q *Queries) UpsertMessage(ctx context.Context, arg UpsertMessageParams) error {
	_, err := q.db.ExecContext(ctx, upsertMessage,
		arg.ID,
		arg.GuildID,
		arg.ChannelID,
		arg.AuthorID,
		arg.MessageType,
		arg.CreatedAt,
		arg.EditedAt,
		arg.DeletedAt,
		arg.Content,
		arg.NormalizedContent,
		arg.ReplyToMessageID,
		arg.Pinned,
		arg.HasAttachments,
		arg.RawJson,
		arg.UpdatedAt,
	)
	return err
}

const upsertMessageEmbedding = `-- name: UpsertMessageEmbedding :exec
insert into message_embeddings(
	message_id, provider, model, input_version, dimensions, embedding_blob, embedded_at
) values(?, ?, ?, ?, ?, ?, ?)
on conflict(message_id, provider, model, input_version) do update set
	dimensions = excluded.dimensions,
	embedding_blob = excluded.embedding_blob,
	embedded_at = excluded.embedded_at
`

type UpsertMessageEmbeddingParams struct {
	MessageID     string
	Provider      string
	Model         string
	InputVersion  string
	Dimensions    int64
	EmbeddingBlob []byte
	EmbeddedAt    string
}

func (q *Queries) UpsertMessageEmbedding(ctx context.Context, arg UpsertMessageEmbeddingParams) error {
	_, err := q.db.ExecContext(ctx, upsertMessageEmbedding,
		arg.MessageID,
		arg.Provider,
		arg.Model,
		arg.InputVersion,
		arg.Dimensions,
		arg.EmbeddingBlob,
		arg.EmbeddedAt,
	)
	return err
}
